### ISSUE TITLE
Timer2 do not work when it has this same value for On and Off

### ISSUE THREAD

**Issue by QbaF** [gablau/node-red-contrib-bigtimer#5]
As stated on [official BigTimer developer webpage](https://tech.scargill.net/big-timer/#comment-67932), some users has problem with working Timer2.

I think the problem occurs when 2nd timer has this same value for On and Off (e.g. 18:00 or Dusk in both fields) regardless of the Offset.

E.g.
DON’T works: On Time2 = 18:00, On Offset2 = 0, Off Time2 = 18:00, Off Offset2 = 15
DO works: ……On Time2 = 18:00, On Offset2 = 0, Off Time2 = 18:15, Off Offset2 = 0

**Comment by QbaF** [comment]
Why it is closed? Because of 2 months of not resolving/replaying?

**Comment by gablau** [comment]
Hi,
this is just a "Unofficial source code mirror of bigtimer".

Sorry but I'm not the original author. 
This code is not related to the NPM package
I put the original source code here, because the original author does not have a repository.
I need it because I made the changes you find in this in this branch
https://github.com/gablau/node-red-contrib-bigtimer/tree/week-override

I can't support the original code, sorry
For any other requests go to: https://tech.scargill.net/big-timer

**Comment by QbaF** [comment]
Ah, ok. Nevermind, that project anyway looks to be dead. Original author does respond sometimes on his blog but removing bugs I never noticed. I thought that some repository for bugs could be useful when someone will decide to develop that however good product but with some errors.
But in this case, I understand You would like to close it. A little bit misleading for people contributing/looking for BigTimer help but understandable.
